# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: KD's Travel Blog
subtitle: Hi, æˆ‘æ˜¯ KD Chang å¼µå‡±è¿ªï¼Œæˆ‘åœ¨é€™æ›¸å¯«æˆ‘çš„æ—…è¡Œç­†è¨˜ | KD æ—…è¡Œéƒ¨è½æ ¼
author: KD Chang å¼µå‡±è¿ª
language:
  - zh-TW
  - en
timezone: Asia/Taipei

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://travel.kdchang.net
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

#Custom Setting Start

# Site settings
SEOTitle: KD's Travel Blog æ—…è¡Œéƒ¨è½æ ¼ | KD Chang å¼µå‡±è¿ª
header-img: img/cover.jpg
email: kdchang.net@gmail.com
description: "KD æ—…è¡Œéƒ¨è½æ ¼ã€‚Hi, æˆ‘æ˜¯ KD Chang å¼µå‡±è¿ªï¼Œæˆ‘åœ¨é€™æ›¸å¯«æˆ‘çš„æ—…è¡Œå°è¦½/ç™»å±±å¥è¡Œç­†è¨˜ã€‚é€™è£¡è¨˜éŒ„ä¸€å€‹è»Ÿé«”å·¥ç¨‹å¸«ä¹Ÿæ˜¯ä¸€ä½ç”¢å“å°ˆæ¡ˆç¶“ç†å’Œæ•™è‚²å·¥ä½œè€…å°æ—…è¡Œçš„æ„ç¾©çš„æ€è€ƒèˆ‡è§€å¯Ÿï¼Œæ­¡è¿ä¸€èµ·äº¤æµè¨è«–ï¼Œè®“é€™å€‹ä¸–ç•Œæ›´åŠ é–‹æ”¾ç¾å¥½ï¼"
keyword: "æ—…è¡Œ,æ—…éŠ,ç™»å±±,å¥è¡Œ,åšç‰©é¤¨,ç¾è¡“é¤¨,å¤è¹Ÿ,å¤§å­¸æ ¡åœ’,å°è¦½"

# SNS settings
# RSS: false
# weibo_username:     Demonbane
# zhihu_username:     Demonbane
github_username: kdchang
twitter_username: kaidichang
instagram_username: kdchang_net
facebook_username: travel.kdchang.net
# linkedin_username: kaidichang

# Build settings
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Disqus settings
# kdchang-blog
disqus_username: kdchang-travel-blog

# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics 4
ga_track_id: G-61P35Y2H2M # Format: UA-xxxxxx-xx
ga_domain: travel.kdchang.net

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "KD Chang å¼µå‡±è¿ªï¼ˆ@kdchangï¼‰ï¼Œå°ç£å¤§å­¸ï¼Œä¸»ä¿®ç¶“æ¿Ÿå­¸ï¼Œè‡ºå¤§è³‡ç®¡æ‰€ç•¢æ¥­ã€‚æ˜¯ä¸€å€‹è»Ÿé«”å·¥ç¨‹å¸«ï¼Œä¹Ÿæ˜¯ä¸€ä½ PM ç”¢å“/å°ˆæ¡ˆç¶“ç†å’Œæ•™è‚²å·¥ä½œè€…ã€‚æ›¾æœå‹™éä¸Šå¸‚ç¶²è·¯è»Ÿé«”å…¬å¸ã€ä¸Šå¸‚ç§‘æŠ€é›»å­å…¬å¸ã€å°ç£ AI äººå·¥æ™ºæ…§æ–°å‰µç¨è§’ç¸å…¬å¸ï¼Œä¹Ÿæ›¾åƒèˆ‡æ•¸å€‹æ–°å‰µçµ„ç¹”çš„å‰µè¾¦å’Œå¤šå€‹ç¶²è·¯ç”¢å“æœå‹™çš„é–‹ç™¼ã€‚A Software Engineer, Product/Project Manager & Educator.:)"
sidebar-avatar: /img/avatar.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: false # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Friends
friends:
  [
    { title: "KD é–±è®€è·å ´äººç”Ÿ ğŸ”–", href: "https://www.kdchang.net" },
    {
      title: "è½å‡ºè·å ´è»Ÿå¯¦åŠ› Podcast",
      href: "https://open.firstory.me/user/soft-skills-hacker",
    },
    { title: "CoderBridge", href: "https://tw.coderbridge.com/" },
    { title: "Yohowto", href: "https://tw.yohowto.com/" },
    {
      title: "travelBridge Weekly æŠ€è¡“é€±åˆŠ",
      href: "http://weekly.travelbridge.cc/",
    },
    { title: "travelBridge Blog", href: "http://blog.travelbridge.cc/" },
  ]

#Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
search_dir: search
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: web
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

## Google Analytics 4
# google_analytics:
#   enable: true
#   id: G-FN9X92SM77
#   site: auto

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog
plugins: hexo-generator-cname
  hexo-generator-robotstxt

## social
addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  instagram: true
  pinterest: true

## robots.txt
robotstxt:
  useragent: "*"
  disallow: ""
  sitemap:
    - https://travel.kdchang.net/sitemap.xml
  baidusitemap:
    - /baidusitemap.xml

## category
category_generator:
  per_page: 10

## archive
archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

## Search
search:
  path: search.xml
  field: post
  content: true
  format: html

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  # repo: https://github.com/ReadThinker/readthinker.github.io
  repo: git@github.com:kdchang-travel-blog/kdchang-travel-blog.github.io.git
  # example, https://github.com/hexojs/hexojs.github.io
  branch: gh-pages
  ignore_hidden: false

# hexo sitemap
sitemap:
  path: sitemap.xml
  template: ./sitemap_template.xml

baidusitemap:
  path: baidusitemap.xml

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -date
  icon: logo.png
  autodiscovery: true
  template:

include: .nojekyll
  CNAME

index_generator:
  per_page: 10
  order_by: -date
  i18n_dir: :lang

menu:
  zh-tw: /
  en: /en/
